from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views_staffclaim, views_travelrequest


urlpatterns = [
    path("", views_staffclaim.index, name="index"),
    path("mysubmission", views_staffclaim.mysubmission, name="mysubmission"),
    path("upload_attachment", views_staffclaim.upload_attachment, name="upload_attachment"),
    path("newsubmission", views_staffclaim.newsubmission, name="newsubmission"),
    path("submitapproval", views_staffclaim.submitapproval, name="submitapproval"),
    path("save_claim_advance_info", views_staffclaim.save_claim_advance_info, name="save_claim_advance_info"),
    path("viewapproval", views_staffclaim.viewapproval, name="viewapproval"),
    path("viewexport", views_staffclaim.viewexport, name="viewexport"),
    path("viewverify", views_staffclaim.viewverify, name="viewverify"),
    path("delete_claim", views_staffclaim.delete_claim, name="delete_claim"),
    path("approve_claim", views_staffclaim.approve_claim, name="approve_claim"),
    path("reject_claim", views_staffclaim.reject_claim, name="reject_claim"),
    path("verify_claim", views_staffclaim.verify_claim, name="verify_claim"),
    path("reject_aclaim", views_staffclaim.reject_aclaim, name="reject_aclaim"),
    path("viewsubmission/<int:claim_id>/", views_staffclaim.viewsubmission, name="viewsubmission"),
    path('deleteclaimline', views_staffclaim.deleteclaimline, name='deleteclaimline'),
    path('finance_edit', views_staffclaim.finance_edit, name='finance_edit'),
    path('edit_claim_line', views_staffclaim.edit_claim_line, name='edit_claim_line'),
    path("setting_currency", views_staffclaim.setting_currency, name="setting_currency"),
    path("setting_analyticcode", views_staffclaim.setting_analyticcode, name="setting_analyticcode"),
    path("setting_profile", views_staffclaim.setting_profile, name="setting_profile"),
    path("setting_department", views_staffclaim.setting_department, name="setting_department"),
    path("delete_department", views_staffclaim.delete_department, name="delete_department"),
    path("delete_analyticcode", views_staffclaim.delete_analyticcode, name="delete_analyticcode"),
    path("setting_expensetype", views_staffclaim.setting_expensetype, name="setting_expensetype"),
    path("delete_expensetype", views_staffclaim.delete_expensetype, name="delete_expensetype"),
    path("export_claims", views_staffclaim.export_claims, name="export_claims"),
    path("send_message", views_staffclaim.send_message, name="send_message"),
    path("login/", LoginView.as_view(template_name="neutrovisinternal/login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/login/"), name="logout"),
    path("new_travel_request", views_travelrequest.new_travel_request, name="new_travel_request"),
    path("my_travel_request", views_travelrequest.my_travel_request, name="my_travel_request"),
    path("view_tr_approval", views_travelrequest.view_tr_approval, name="view_tr_approval"),
    path("submit_travel_request", views_travelrequest.submit_travel_request, name="submit_travel_request"),
    path("delete_tr_line", views_travelrequest.delete_tr_line, name="delete_tr_line"),
    path("edit_tr_line", views_travelrequest.edit_tr_line, name="edit_tr_line"),
    path("approve_travel_request", views_travelrequest.approve_travel_request, name="approve_travel_request"),
    path("delete_travel_request", views_travelrequest.delete_travel_request, name="delete_travel_request"),
    path("reject_travel_request", views_travelrequest.reject_travel_request, name="reject_travel_request"),
    path("ol_approval_traval_request", views_travelrequest.ol_approval_traval_request, name="ol_approval_traval_request"),
    path("ol_reject_traval_request", views_travelrequest.ol_reject_traval_request, name="ol_reject_traval_request"),
    path("view_travel_request/<int:travel_id>/", views_travelrequest.view_travel_request, name="view_travel_request"),
    path("password_change", views_staffclaim.password_change, name="password_change"),
    path("password_reset_request", views_staffclaim.password_reset_request, name="password_reset_request"),
    path('reset/<uidb64>/<token>', views_staffclaim.password_reset_confirm, name='password_reset_confirm'),
]
